### ISSUE TITLE
Lucee 5 abstract errors on ORMUtilSupport

### ISSUE THREAD

**Issue by elpete** [coldbox-modules/cbox-cborm#19]
https://github.com/coldbox-modules/cbox-cborm/blob/development/modules/cborm/models/util/ORMUtilSupport.cfc#L11

This line prevents ColdBox from starting on Lucee 5.  Not sure if it is a fix here or in WireBox, but wanted to create the issue nonetheless.

**Comment by bdw429s** [comment]
If I recall, Micha fixed the issues with this in Lucee fairly recently.  The problem was that when Wirebox tried to get metadata for the CFC with `getComponentMetadata()`, Lucee would instantiate the compnent in the background which would throw an exception since the component was abstract.  

Here we go: https://luceeserver.atlassian.net/browse/LDEV-1042
Looks like he rolled out the fix in Lucee `5.1.1.1`.

That said, it might not hurt for us remove that for now just to prevent people on Lucee 5.0 or 5.1.0 from getting errors.

**Comment by lmajano** [comment]
THat was committed by Micha himself a while back.  I see no point in it, we can remove it.

**Comment by lmajano** [comment]
it is building right now.  It has auto-publish
so all we need to do for a release now is make sure we merge to master
